Sys.sleep(0.000000)
options(BatchJobs.on.slave=TRUE)
library(BatchJobs)
BatchJobs:::doJob(
	reg=loadRegistry('/home/lang/vcs/batchjobs/trunk/BatchExperiments/skel/inst/tests/runit_files'),
	ids=c(2L),
	multiple.result.files=FALSE,
	disable.mail=FALSE,
	first=1,
	last=3)
BatchJobs:::setOnSlave(FALSE)